### PR TITLE
Fix for no value if [Option] arg equals to [Value] arg

### LINKED ISSUE #398: No value or parsing error if [Option] arg equals to [Value] arg
Example:
```
class SameOptionAndPosValueArgs
{
	[Option('u', "unit")]
	public string OptValue { get; set; }

	[Value(0)]
	public string PosValue { get; set; }
}

[Fact]
public void SameOptionAndPosValue()
{
	var parser = Parser.Default;
	var result = parser.ParseArguments<SameOptionAndPosValueArgs>(
		new[] { "arg", "-u", "arg" }); // !!! pos and value are "arg"
	result
		.WithNotParsed(errors => { throw new InvalidOperationException("Must be parsed."); })
		.WithParsed(args =>
		{
			Assert.Equal("arg", args.OptValue);
			Assert.Equal("arg", args.PosValue); // !!! args.PosValue is null
		});
}
```

When user enters same values for [Option] and [Value] args, parser is losing one of it because they are equal tokens.

[TokenPartitioner.cs](TokenPartitioner.cs#25) has code:
```
var nonOptions = tokenList
    .Where(t => !switches.Contains(t))
    .Where(t => !scalars.Contains(t))
    .Where(t => !sequences.Contains(t)).Memorize();
var values = nonOptions.Where(v => v.IsValue()).Memorize();
var errors = nonOptions.Except(values).Memorize();
```
One of tokens for "-u" option is already in `scalars` variable so `Where` is filtering out both tokens with "arg" and then its not gettings into `values`. Filtering is happening because all tokens classes have `IEqualtable<T>` so "arg" == "arg" but it is two different items in memory.

One of solutions: make reference comparing, not `IEqutable<T>`. .Net doesn't have such comparer. Stackoverflow helps:
```
internal sealed class ReferenceEqualityComparer : IEqualityComparer, IEqualityComparer<object>
{
	public static readonly ReferenceEqualityComparer Default = new ReferenceEqualityComparer();

	public new bool Equals(object x, object y)
	{
		return x == y; // reference equality because operator== is static and resolved at compile-time
	}

	public int GetHashCode(object obj)
	{
		return RuntimeHelpers.GetHashCode(obj);
	}
}
```

Pass this comparer to `Contains` and `Except`:
```
var nonOptions = tokenList
	.Where(t => !switches.Contains(t, ReferenceEqualityComparer.Default))
	.Where(t => !scalars.Contains(t, ReferenceEqualityComparer.Default))
	.Where(t => !sequences.Contains(t, ReferenceEqualityComparer.Default)).Memorize();
var values = nonOptions.Where(v => v.IsValue()).Memorize();
var errors = nonOptions.Except(values, ReferenceEqualityComparer.Default).Cast<Token>().Memorize();
```

### PR DESCRIPTION
**Pull request by zii-dmg**
Make comparisons by reference in TokenPartitioner. Fixes #398.

### CODE REVIEW

File: src/CommandLine/Core/TokenPartitioner.cs [hunk 1]
```diff
@@ -23,11 +24,11 @@ public static
...
             var nonOptions = tokenList
-                .Where(t => !switches.Contains(t))
-                .Where(t => !scalars.Contains(t))
-                .Where(t => !sequences.Contains(t)).Memorize();
+                .Where(t => !switches.Contains(t, ReferenceEqualityComparer.Default))
+                .Where(t => !scalars.Contains(t, ReferenceEqualityComparer.Default))
+                .Where(t => !sequences.Contains(t, ReferenceEqualityComparer.Default)).Memorize();
             var values = nonOptions.Where(v => v.IsValue()).Memorize();
-            var errors = nonOptions.Except(values).Memorize();
+            var errors = nonOptions.Except(values, ReferenceEqualityComparer.Default).Cast<Token>().Memorize();
```
Comment (nemec) [inline src/CommandLine/Core/TokenPartitioner.cs]: Are you casting back to Token because the comparer casts everything into Object? What if you made the comparer inherit `IEqualityComparer<Token>` and then called [Object.ReferenceEquals](https://msdn.microsoft.com/en-us/library/system.object.referenceequals(v=vs.110\).aspx) in the implementation rather than `==`? That's a bit more explicit too, and wouldn't need a comment explaining that we're aiming for reference equality on line 16.

Comment (zii-dmg) [inline src/CommandLine/Core/TokenPartitioner.cs]: I realized that I can make other cast - `(IEqualityComparer<Token>)ReferenceEqualityComparer.Default` so `Cast<Token>` will not be needed. Or can make modify comparer to classic generic version - `ReferenceEqualityComparer<T>`. Don't want to inherit `IEqualityComparer<Token>`, it's too concrete for this task.

Will replace `==` with `ReferenceEquals`.

Comment (nemec) [inline src/CommandLine/Core/TokenPartitioner.cs]: Generic sounds good to me. Any time we can make the type system work for us is a win in my book 😃

Comment (zii-dmg) [inline src/CommandLine/Core/TokenPartitioner.cs]: But reference comparer doesn't have to be generic because it compares references anyway. I used [this implementation from stackoverflow](http://stackoverflow.com/a/35520207). As author says it's using contravariance feature so we can cast comparer to any type of IEqualityComparer<T>.

**Comment by zii-dmg** [comment]
If you really want `ReferenceEqualityComparer<T>` I will make it, just say. Waiting for answer.

**Comment by nemec** [comment]
Looks good

**Comment by zii-dmg** [comment]
I accidently removed FactAttribute from [last test](https://github.com/gsscoder/commandline/blob/master/tests/CommandLine.Tests/Unit/ParserTests.cs#L837) with merge. Can you restore it?

**Comment by nemec** [comment]
Fixed
